---
  - name: 'Baixa o arquivo de instalacao do Wordpress'
    get_url:
      url: https://br.wordpress.org/wordpress-5.1-pt_BR.tar.gz
      dest: '/tmp/wordpress.tar.gz'

  - name: 'Descompacta o wordpress'
    unarchive:
      remote_src: yes
      src: '/tmp/wordpress.tar.gz'
      dest: /var/www/
    become: yes

  - name: Copy a "sudoers" file on the remote machine for editing
    copy:
      src: "{{ wp_installation_dir }}/wp-config-sample.php"
      dest: "{{ wp_installation_dir }}/wp-config.php"
      remote_src: yes
    become: yes
  
  - name: 'Configura o wp-config com as entradas do banco de dados'     
    replace:
      path: "{{ wp_installation_dir }}/wp-config.php"
      regexp: "{{ item.regex }}"
      replace: "{{ item.value }}"
      backup: yes
    with_items:
      - { regex: 'nome_do_banco_de_dados_aqui', value: "{{ wp_db_name }}"}
      - { regex: 'nome_de_usuario_aqui', value: "{{ wp_username }}"}
      - { regex: 'senha_aqui', value: "{{ wp_user_password }}"}
      - { regex: 'localhost', value: "{{ wp_db_ip }}"}
    become: yes


  - name: 'Configura apache para servir Wordpress'
    template:
      src: 'templates/000-default.conf.j2'
      dest: '/etc/apache2/sites-available/000-default.conf'
    become: yes
    notify:
      - restart apache
